---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll
  labels:
    app: jekyll
spec:
  type: NodePort
  selector:
    run: jekyll
  ports:
    - name: 4000-8080
      nodePort: 30097
      port: 8080
      protocol: TCP
      targetPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  namespace: development
  name: jekyll
  labels:
    run: jekyll
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      command:
        - jekyll
        - new
        - /site
      volumeMounts:
        - mountPath: /site
          name: site
  containers:
    - name: jekyll
      image: kodekloud/jekyll-serve
      volumeMounts:
        - mountPath: /site
          name: site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: jekyll-site
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ''
  volumeName: jekyll-site
