---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  labels:
    app: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - name: "30095"
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          volumeMounts:
            - name: data
              mountPath: /data
          command:
            - /bin/bash
            - -c
          args:
            - cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R
      containers:
        - image: drupal:8.6
          name: drupal
          volumeMounts:
            - name: data
              mountPath: /var/www/html/profiles
              subPath: profiles
            - name: data
              mountPath: /var/www/html/sites
              subPath: sites
            - name: data
              mountPath: /var/www/html/modules
              subPath: modules
            - name: data
              mountPath: /var/www/html/themes
              subPath: themes
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: drupal-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /drupal-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: drupal-mysql-pv
